import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Core Systems',
      items: [{type: 'autogenerated', dirName: 'core-systems'}],
    },
    {
      type: 'category',
      label: 'Abilities',
      items: [{type: 'autogenerated', dirName: 'abilities'}],
    },
    {
      type: 'category',
      label: 'Quirks',
      items: [{type: 'autogenerated', dirName: 'quirks'}],
    },
    {
      type: 'category',
      label: 'Genes',
      items: [{type: 'autogenerated', dirName: 'genes'}],
    },
  ],
};

export default sidebars;
